"""Build Field Guide tokens into CSS custom properties.

Source of truth: field-guide/tokens/*.json (W3C design-tokens shape: $value,
$type, {reference.paths}). Output: field-guide/dist/tokens.css.

Plain Python on purpose: the app deploys on Render with a pip-only build, so
the token build can't depend on Node. The JSON stays in the standard shape,
so Style Dictionary or a Figma variables sync can read the same files later.

    python field-guide/build.py          # regenerate dist/tokens.css
    python field-guide/build.py --check  # exit 1 if dist/ is out of date (CI)
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TOKENS_DIR = ROOT / "tokens"
OUT = ROOT / "dist" / "tokens.css"
PREFIX = "fg"
REF = re.compile(r"^\{([^}]+)\}$")


def load_tokens():
    tree = {}
    for path in sorted(TOKENS_DIR.glob("*.json")):
        data = json.loads(path.read_text())
        for key, value in data.items():
            if not key.startswith("$"):
                tree[key] = value
    return tree


def flatten(node, path=(), inherited_type=None, out=None):
    """Walk the tree and collect {dotted.path: (value, type, extensions)}."""
    if out is None:
        out = {}
    node_type = node.get("$type", inherited_type)
    if "$value" in node:
        out[".".join(path)] = (node["$value"], node_type, node.get("$extensions", {}))
        return out
    for key, child in node.items():
        if not key.startswith("$") and isinstance(child, dict):
            flatten(child, path + (key,), node_type, out)
    return out


def resolve(value, tokens, seen=()):
    if isinstance(value, str):
        match = REF.match(value)
        if match:
            ref = match.group(1)
            if ref in seen:
                raise ValueError(f"circular token reference: {' -> '.join(seen + (ref,))}")
            if ref not in tokens:
                raise KeyError(f"unknown token reference {{{ref}}}")
            return resolve(tokens[ref][0], tokens, seen + (ref,))
    return value


def hex_with_alpha(hex_value, alpha):
    h = hex_value.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
    return f"rgb({r} {g} {b} / {alpha})"


def to_css(value, token_type, extensions):
    alpha = extensions.get("fieldguide.alpha")
    if token_type == "color" and alpha is not None:
        return hex_with_alpha(value, alpha)
    if token_type == "fontFamily" and isinstance(value, list):
        return ", ".join(f'"{f}"' if " " in f else f for f in value)
    return str(value)


def css_name(path):
    return f"--{PREFIX}-" + path.replace(".", "-")


def build():
    tokens = flatten(load_tokens())
    lines = [
        "/* GENERATED by field-guide/build.py from field-guide/tokens/*.json. Do not edit by hand. */",
        ":root {",
    ]
    group = None
    for path, (value, token_type, extensions) in tokens.items():
        top = path.rsplit(".", 1)[0]
        if top != group:
            lines.append(f"\n  /* {top} */")
            group = top
        resolved = resolve(value, tokens)
        css = to_css(resolved, token_type, extensions)
        ref = REF.match(value) if isinstance(value, str) else None
        # Keep palette references live so a palette change cascades at runtime too.
        if ref and token_type == "color" and "fieldguide.alpha" not in extensions:
            css = f"var({css_name(ref.group(1))})"
        lines.append(f"  {css_name(path)}: {css};")
    lines.append("}\n")
    return "\n".join(lines)


def main():
    css = build()
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != css:
            print("field-guide/dist/tokens.css is out of date. Run: python field-guide/build.py")
            sys.exit(1)
        print("tokens.css is up to date")
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(css)
    print(f"wrote {OUT.relative_to(ROOT.parent)}")


if __name__ == "__main__":
    main()
